version: "3.8"

services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
